services:
  db:
    ports:
      - "127.0.0.1:5432:5432"
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: k2db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d k2db"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
      - web
    expose:
      - "8080"
    volumes:
      # Mounta configen in i containern
      - ./secrets/config.json:/app/config.json:ro
    environment:
      OCR_USE_OCRMY: "0"
      TZ: Europe/Stockholm

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web

volumes:
  pgdata:
  caddy_data:
  caddy_config:

networks:
  internal:
    internal: true
  web:

